name: Spellcheck
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spellcheck
        uses: redis-stack/github-actions/spellcheck@main
        env:
          DICTIONARY: dictionary.txt
          DOCS_DIRECTORY: docs